export const educations = [
    {
        school: "University of Yaounde 1",
        href: "https://uy1.uninet.cm/",
        degree: "Master's in Software Engineering",
        logoUrl: "/uy1.png",
        start: "Oct 2023",
        end: "Present",
        current: true,
    },
    {
        school: "University of yaounde 1",
        href: "https://uy1.uninet.cm/",
        degree: "Bachelor Degree in Computer Science(Software Engineer)",
        logoUrl: "/uy1.png",
        start: "Oct 2020",
        end: "Jul 2023",
    },
    {
        school: "Government bilingual high school yaounde",
        href: "#",
        degree: "GCE Advanced Level",
        logoUrl: "",
        start: "Sep 2019",
        end: "Jun 2020",
    },
    {
        school: "Government bilingual high school yaounde",
        href: "#",
        degree: "GCE Ordinary Level",
        logoUrl: "",
        start: "Sep 2017",
        end: "Jun 2018",
    },
]