export const portfolioData = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "TOMDIEU TCHADIEUKO IVAN GOTTFRIED",
  alternateName: "Tomdieu Ivan",
  jobTitle: "Software Developer",
  url: "https://ivantomdieu.vercel.app/",
  sameAs: [
    "https://www.linkedin.com/in/tomdieuivan/",
    "https://github.com/Tomdieu",
  ],
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "Work",
    email: "mailto:ivan.tomdieu@gmail.com",
    // telephone: "+237650039773",
  },
  skills: [
    "React",
    "Next.js",
    "Typescript",
    "Javascript",
    "Node.js",
    "Python",
    "Postgres",
    "Docker",
    "Kubernetes",
    "Java",
    "Django Rest Framework",
    "Ontology Web Language",
    "Prisma",
    "Tailwindcss",
    "React Native",
    "Expo",
    "Sequelize",
    "Websockets",
    "Uml",
  ],
  educations: [
    {
      "@type": "EducationalOrganization",
      name: "University of Yaounde 1",
      url: "https://uy1.uninet.cm/",
      degree: "Master 1",
      logoUrl: "/uy1.png",
      startDate: "Oct 2023",
      endDate: "Jul 2024",
    },
    {
      "@type": "EducationalOrganization",
      name: "University of Yaounde 1",
      url: "https://uy1.uninet.cm/",
      degree: "Bachelor Degree in Computer Science (Software Engineer)",
      logoUrl: "/uy1.png",
      startDate: "Oct 2020",
      endDate: "Jul 2023",
    },
    {
      "@type": "EducationalOrganization",
      name: "Government Bilingual High School Yaounde",
      degree: "GCE Advanced Level",
      startDate: "Sep 2019",
      endDate: "Jun 2020",
    },
    {
      "@type": "EducationalOrganization",
      name: "Government Bilingual High School Yaounde",
      degree: "GCE Ordinary Level",
      startDate: "Sep 2017",
      endDate: "Jun 2018",
    },
  ],
  experiences: [
    {
      "@type": "Organization",
      name: "Coding Industry Sarl",
      url: "http://coding-industry.com/fr_fr/",
      location: "Remote",
      jobTitle: "Backend Developer",
      logoUrl: "./coding-industry.png",
      startDate: "Jun 2024",
      endDate: "Present",
      description: `
          Full Stack Developer.
          At Coding Industry, I specialize in building comprehensive full-stack applications. My key responsibilities include:
          - Backend Development: Crafting and maintaining scalable and efficient server-side logic using Django.
          - Frontend Development: Creating dynamic and responsive user interfaces with Next.js and React.
        `,
    },
    {
      "@type": "Organization",
      name: "Sciences de la Professionnalisation",
      url: "https://esso-idp.com/",
      location: "Remote",
      jobTitle: "Fullstack Developer",
      logoUrl: "./esso-idp.jpg",
      startDate: "Aug 2023",
      endDate: "Present",
      description: "",
    },
    {
      "@type": "Organization",
      name: "Revolution Travel & Services",
      url: "https://www.facebook.com/p/Revolution-Travel-Services-100064125607997/",
      location: "Ngousso",
      jobTitle: "Travel Consultant",
      startDate: "Sep 2024",
      endDate: "Present",
      description:
        "At Revolution Travel & Services, my primary responsibility is to book and sell airline tickets.",
    },
  ],
};
